package com.mechforge.core.units

enum class UnitFamily(val displayName: String) {
    PRESSURE("Pressure"),
    PRESSURE_GRADIENT("Pressure Gradient"),
    FLOW("Flow"),
    POWER("Power"),
    LENGTH("Length"),
    TEMPERATURE("Temperature"),
    MASS("Mass"),
    MASS_PER_LENGTH("Mass per Length"),
    DENSITY("Density"),
    VELOCITY("Velocity"),
    KINEMATIC_VISCOSITY("Kinematic Viscosity"),
    DYNAMIC_VISCOSITY("Dynamic Viscosity"),
    ROTATIONAL_SPEED("Rotational Speed"),
    TORQUE("Torque"),
    VOLUME("Volume"),
    SPECIFIC_VOLUME("Specific Volume"),
    AREA("Area"),
    MOLAR_MASS("Molar Mass"),
    REVOLUTIONS("Revolutions"),
    TIME("Time"),
    MASS_FLOW("Mass Flow"),
    STIFFNESS("Stiffness"),
    FORCE("Force"),
    LINE_LOAD("Line Load"),
    SECOND_MOMENT("Second Moment of Area"),
    SECTION_MODULUS("Section Modulus"),
    ENERGY("Energy"),
    SPECIFIC_HEAT("Specific Heat"),
    HEAT_TRANSFER_COEFF("Heat Transfer Coefficient"),
    TEMPERATURE_DIFFERENCE("Temperature Difference"),
    DIMENSIONLESS("Dimensionless"),
}
